# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BoldTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BoldTest
  pod 'Alamofire', '~> 5.2'
  pod 'Kingfisher', '~> 6.0'

  target 'BoldTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BoldTestUITests' do
    # Pods for testing
  end

end
